// PRE-BUILD:
// This file is generated by shaderheadergen.
// Don't modify this file. Instead, modify the associated shader files.
// shaderheadergen will automatically find all files located in 'Source\Shaders\' and add them here.



#include "Shaders/Basic.vert"
#include "Shaders/Colormap.frag"
#include "Shaders/Combine.frag"
#include "Shaders/Common.frag"
#include "Shaders/Dot.frag"
#include "Shaders/Dot.vert"
#include "Shaders/Line.frag"
#include "Shaders/Line.vert"
#include "Shaders/LinePlusDot.frag"
#include "Shaders/Texture.frag"
